//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle_sell_book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public string MAHD { get; set; }
        public string MASACH { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
