//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle_sell_book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIET_KE_SACH
    {
        public string Ma_sach { get; set; }
        public string Ten_sach { get; set; }
        public string Hinh_anh { get; set; }
        public string Mo_ta_sach { get; set; }
        public Nullable<decimal> Gia_ban { get; set; }
        public string Tac_gia { get; set; }
    }
}
