//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle_sell_book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIET_KE_HOA_DON
    {
        public string Ma_hoa_don { get; set; }
        public string Ma_khach_hang { get; set; }
        public System.DateTime Ngay_lap_hd { get; set; }
        public string Trang_thai { get; set; }
    }
}
