//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle_sell_book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIET_KE_CHU_DE
    {
        public string Ma_chu_de { get; set; }
        public string Ten_chu_de { get; set; }
        public string Mo_ta_chu_de { get; set; }
    }
}
