//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle_sell_book.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public string MASACH { get; set; }
        public string TENSACH { get; set; }
        public string HINHANH { get; set; }
        public string MOTA { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public string MACD { get; set; }
        public string MANXB { get; set; }
        public System.DateTime NAMXB { get; set; }
        public string MATG { get; set; }
    
        public virtual CHUDE CHUDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual NXB NXB { get; set; }
        public virtual TACGIA TACGIA { get; set; }
    }
}
